name: Test Telegram

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug env
        run: env | sort

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          echo "BOT_TOKEN present?"
          if [ -z "$BOT_TOKEN" ]; then echo "NO"; else echo "YES"; fi

          echo "CHAT_ID present?"
          if [ -z "$CHAT_ID" ]; then echo "NO"; else echo "YES"; fi

          python3 script.py
